apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blogger-api
      process: web
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blogger-api-web
  strategy:
    canary:
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      stableMetadata:
        annotations:
          role: stable
        labels:
          role: stable
      trafficRouting:
        istio:
          virtualService: 
            name: blogger-vs
          destinationRule:
            name: blogger-dr    
            canarySubsetName: canary  
            stableSubsetName: stable  
      steps:
      - setWeight: 5
      - pause:
          duration: 10m