apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService: 
            name: blogger-vs
          destinationRule:
            name: blogger-dr    
            canarySubsetName: v2  
            stableSubsetName: v1  
      steps:
      - setWeight: 5
      - pause:
          duration: 10m