apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blogger-api
      process: web
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: blogger-api-web
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService: 
            name: blogger-vs
          destinationRule:
            name: blogger-dr    
            canarySubsetName: v2  
            stableSubsetName: v1  
      steps:
      - setWeight: 5
      - pause:
          duration: 10m